version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    reviewers:
      - 'zfixler'
    assignees:
      - 'zfixler'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      all-dependencies:
        patterns:
          - '*'
